// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("app", ['ionic']).controller("helloCtrl", function($scope) {
    $scope.hello = "fuck";
    return console.log("loaded");
  }).run(function($rootScope) {
    return $rootScope.test = "fuck you";
  });

}).call(this);

//# sourceMappingURL=app.map
