// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("food.ControlPanel", ['ui.sortable']).controller("cpCtrl", [
    "$scope", function($s) {
      $s.items = [
        {
          "id": '001',
          "name": "hello",
          "list": {
            "01": 1,
            "02": 2
          }
        }, {
          "id": "002",
          "name": "bello",
          "list": {
            "01": 1,
            "02": 3
          }
        }, {
          "id": "003",
          "name": "kello",
          "list": {
            "01": 1,
            "02": 3
          }
        }
      ];
      $s.oldList = [];
      return $s.sortableOption = {
        update: function() {
          return console.log("update", $s.items);
        },
        stop: function() {
          return console.log("stop", $s.items);
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=app.map
