// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("Orcid", ['ionic']).config([
    "$stateProvider", "$urlRouterProvider", function($stateProvider, $urlRouterProvider) {
      $stateProvider.state('tabs', {
        url: '/tab',
        abstract: true,
        templateUrl: 'partials/tabs.html'
      }).state('tabs.home', {
        url: '/home',
        views: {
          'home-tab': {
            templateUrl: 'partials/home.html',
            controller: 'checkoutCtrl'
          }
        }
      }).state('tabs.home.list1', {
        url: '/list1',
        views: {
          'home-tab': {
            template: 'List 1'
          }
        }
      }).state('tabs.home.list2', {
        url: '/list2',
        views: {
          'home-tab': {
            template: 'List 2'
          }
        }
      });
      return $urlRouterProvider.otherwise("/tab/home");
    }
  ]).controller("tabCtrl", ["$scope", function($scope) {}]).controller("checkoutCtrl", [
    "$scope", "$rootScope", "$timeout", function($scope, $rootScope, $timeout) {
      $scope.foods = ["list1", "list2", "test3"];
      return $scope.hello = "hello";
    }
  ]);

}).call(this);

//# sourceMappingURL=script.map
