// Generated by CoffeeScript 1.6.3
(function() {
  var app, db, express, io;

  express = require("express");

  io = require("socket.io").listen(3030);

  db = require("mongoskin").db('localhost:12345', {
    database: 'doodlePoll',
    safe: false
  });

  app = new express();

  app.use(express["static"](__dirname + "/public"));

  app.listen(3000);

}).call(this);

//# sourceMappingURL=server.map
