// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("app", ['ionic', 'monospaced.qrcode']).controller("myCtrl", function($scope) {
    return $scope.test = "hello world";
  });

}).call(this);

//# sourceMappingURL=app.map
