// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  express = require("express");

  app = new express();

  app.get("/state1", function(req, res) {
    return res.sendfile(__dirname + "/index.html");
  });

  app.get("/state2/*", function(req, res) {
    return res.sendfile(__dirname + "/index.html");
  });

  app.use("/", express["static"](__dirname + "/"));

  app.listen(3000);

  console.log("listening @ 3000");

}).call(this);

//# sourceMappingURL=server.map
