// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module("APP", ["ui.router"]);

  app.config(function($stateProvider, $urlRouterProvider, $locationProvider) {
    $locationProvider.html5Mode(true);
    return $stateProvider.state("state1", {
      url: "/state1",
      templateUrl: "partials/state1.html"
    }).state("state2", {
      url: "/state2",
      templateUrl: "partials/state2.html"
    }).state("state2.list", {
      url: "/list",
      templateUrl: "partials/state2.list.html",
      controller: function($scope) {
        return $scope.list = ["abc", "cde", "def"];
      }
    });
  });

}).call(this);

//# sourceMappingURL=test.map
