// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  express = require("express");

  app = new express();

  app.use(express["static"](__dirname + "/"));

  app.listen(3000);

  console.log("its running at port 3000");

}).call(this);

//# sourceMappingURL=server.map
