// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, m, path;

  require("coffee-script");

  path = require("path");

  require("./io");

  m = require("mongoskin").db("localhost:12345", {
    database: "food",
    safe: false
  });

  express = require("express");

  app = new express();

  app.use(express.bodyParser());

  app.post("/changePosition", function(req, res) {
    console.log(req.body);
    return m.collection("position").insert({
      hello: "world"
    });
  });

  app.use(express["static"](path.resolve(__dirname + "/../")));

  app.listen(3000);

}).call(this);

//# sourceMappingURL=server.map
