// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var test;
    $(document).on("DOMNodeInserted", "img", function(event) {
      return $(event.target).addClass("ani");
    });
    $('button').on("click", function() {
      return setInterval(function() {
        var randNum;
        randNum = Math.round(500 * Math.random(), 0);
        return $('body').prepend("<img src='http://placekitten.com/" + randNum + "/" + randNum + "' alt=''/>");
      }, 2000);
    });
    test = function(a, b, c) {
      if (c == null) {
        c = 'fuck';
      }
      console.log(a);
      console.log(b);
      return console.log(c);
    };
    return test('abc', 'dasdasd', null);
  });

}).call(this);

//# sourceMappingURL=app.map
