// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $("p").css("color", "red");
    $("p").html("<b>brain</b>fuck");
    $("a.test1").css("opacity", "0.5");
    $("#container > .red").css({
      color: "red",
      background: "orange"
    });
    return $('ul>li:nth-child(3n)').css({
      color: "green"
    });
  });

}).call(this);

//# sourceMappingURL=app.map
