// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var i;
    i = 100;
    $(".btn").tooltip({
      title: "what the fuck",
      placement: "bottom"
    });
    return console.log("hello world");
  });

}).call(this);

//# sourceMappingURL=app2.map
