// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app) {
    app.get("/", function(req, res) {
      console.log(req.session["data"]);
      return res.render("index", {
        test: req.session["data"]
      });
    });
    app.get("/session", function(req, res) {
      console.log(req.sessionID);
      req.session["data"] = "1234567";
      return res.send("just check session");
    });
    return app.get("/tpl/:name.html", function(req, res) {
      var name;
      name = req.params.name;
      return res.render("tpl/" + name + ".jade");
    });
  };

}).call(this);

//# sourceMappingURL=routes.map
