// Generated by CoffeeScript 1.6.3
(function() {
  var fn;

  fn = function() {
    var io;
    io = require("socket.io").listen(3001);
    io.set("log level", 0);
    return io.sockets.on("connection", function(socket) {
      return socket.emit("hello", {
        "welcome": true
      });
    });
  };

  module.exports = fn;

}).call(this);

//# sourceMappingURL=socket.map
